spring.application.name=urlshortener
server.port=1999
spring.datasource.url=jdbc:mysql://mysql-2b3c308d-gamersparadise0007-6b96.b.aivencloud.com:24493/url_mapping?useSSL=true&requireSSL=true
spring.datasource.username=${URLSHORTENER_DB_USER_NEW}
spring.datasource.password=${URLSHORTENER_DB_PASSWORD_NEW}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Application logs are shown in the console
logging.level.com.DeatHertZ.urlshortener=INFO